version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
      - ./mariadb/conf/my.cnf:/etc/mysql/my.conf

    ports:
      - "3306:3306"